############# English navigation ##############
# main menu    
[[main]]
name = "Experiencia"
URL = "experiencia"
weight = 2

[[main]]
name = "Otros Servicios"
URL = "otros-servicios"
weight = 3

[[main]]
name = "Cómo Funciona"
URL = "como-funciona"
weight = 4
  
[[main]]
name = "Equipo"
URL = "equipo"
weight = 5

[[main]]
name = "Contacto"
URL = "contacto"
weight = 6


#Footer menu

[[footer]]
name = "Experiencia"
URL = "experiencia"
weight = 1

[[footer]]
name = "Otros Servicios"
URL = "otros-servicios"
weight = 2

[[footer]]
name = "Cómo Funciona"
URL = "como-funciona"
weight = 3

[[footer]]
name = "Equipo"
URL = "equipo"
weight = 4

[[footer]]
name = "Contacto"
URL = "contacto"
weight = 5