############# English navigation ##############
# main menu    
[[main]]
name = "Energía Empresarial"
URL = "energia-empresarial"
weight = 2
  
[[main]]
name = "Nosotros"
URL = "nosotros"
weight = 3

[[main]]
name = "Contacto"
URL = "contacto"
weight = 5


#Footer menu

[[footer]]
name = "Energía Empresarial"
URL = "energia-empresarial"
weight = 1

[[footer]]
name = "Nosotros"
URL = "nosotros"
weight = 2

[[footer]]
name = "Contacto"
URL = "contacto"
weight = 3