#################### default parameters ################################
# favicon
favicon = "images/favicon.ico"
favicon_32x32 = "images/favicon.ico"
favicon_16x16 = "images/favicon.ico"
apple_touch_icon = "images/favicon.ico"
# logo
logo = "images/logo-capital-power.png"
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Capital Power"
image = "images/logo-capital-power.png" # this image will be used as fallback if a page has no image of its own
# contact info
address = "Av. Américo Vespucio Norte 2700, of 901, Vitacura, Santiago de Chile"
mobile = "+211234565523"
email = "contacto@capitalpower.cl"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "Your ID"
# main sections
mainSections = ["blog"]
# search
search = false
# custom script on header
custom_script= ""


# Preloader
[preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "sign up"
link = "#"

# Subscription
[subscription]
enable = true
# mailchimp subsciption
mailchimp_form_action = "https://capitalpower.us5.list-manage.com/subscribe/post?u=61def603f98cfdcf5528ef732&amp;id=db991a80d7" # replace this url with yours
mailchimp_form_name = "b_61def603f98cfdcf5528ef732_db991a80d7" # replace this code with yours

# google map
[gmap]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
map_marker_label = "Capital Power"
map_zoom = 17

# cookies
[cookies]
enable = true
expire_days = 2
content = "Este sitio utiliza cookies. Si acepta o continúa navegando, consideramos que acepta su uso."
button = "Acepto"

############################# social site ########################
## [[social]]
## title = "facebook"
## icon = "fab fa-facebook" # fontawesome icon pack : https://fontawesome.com/icons/
## link = "#"

## [[social]]
## title = "twitter"
## icon = "fab fa-twitter" # fontawesome icon pack : https://fontawesome.com/icons/
## link = "#"

## [[social]]
## title = "instagram"
## icon = "fab fa-instagram" # fontawesome icon pack : https://fontawesome.com/icons/
## link = "#"

## [[social]]
## title = "github"
## icon = "fab fa-github" # fontawesome icon pack : https://fontawesome.com/icons/
## link = "#"

## [[social]]
## title = "linkedin"
## icon = "fab fa-linkedin-in" # fontawesome icon pack : https://fontawesome.com/icons/
## link = "#"